"""empty message

Revision ID: 584ce5d9808b
Revises: 8fc374c58ac7
Create Date: 2020-01-16 18:02:52.636550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584ce5d9808b'
down_revision = '8fc374c58ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('country', sa.String(length=45), nullable=True))
    op.add_column('trip', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'name')
    op.drop_column('plate', 'country')
    # ### end Alembic commands ###
